name: json_builder
description: A powerful and intuitive library for building and manipulating JSON structures in Dart.
version: 1.0.0
homepage: https://github.com/Ashraf-Hamdoun/JSON-Builder
repository: https://github.com/Ashraf-Hamdoun/JSON-Builder.git
issue_tracker: https://github.com/Ashraf-Hamdoun/JSON-Builder/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.16.0
  lints: ^6.0.0
