name: json_builder_pro
version: 1.1.0
description: A powerful and intuitive Dart package for programmatically building, manipulating, and parsing JSON structures using a tree-based, object-oriented approach.
homepage: https://github.com/Ashraf-Hamdoun/JSON-Builder-Pro
repository: https://github.com/Ashraf-Hamdoun/JSON-Builder-Pro.git
issue_tracker: https://github.com/Ashraf-Hamdoun/JSON-Builder-Pro/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:


dev_dependencies:
  test: ^1.16.0
  lints: ^6.0.0
